name: PR
on:
  pull_request:
    types:
    - opened
    - edited
    - ready_for_review
    - reopened
    - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v3
    - name: Checkout current git repository
      uses: actions/checkout@v3
    - name: Install npm dependencies
      run: npm i
    - name: Run Danger
      run: node_modules/.bin/danger ci -d dangerfile.cjs
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN_OPEN_SOURCE }}
