name: Publish
on:
  release:
    types:
    - published
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        required: true
jobs:
  publish:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_npm-publish.yaml
