name: Release
on:
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  release:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_release.yaml
    with:
      publish: true
